<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sahabat Sekolah | Sekolah Aman, Semua Nyaman</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body class="landing-page">
<header class="landing-nav"><a class="landing-brand" href="{{ route('landing') }}"><span class="landing-logo"><i data-lucide="heart-handshake"></i></span><span><strong>Sahabat<br>Sekolah</strong><small>Sekolah Aman, Semua Nyaman</small></span></a><nav class="landing-desktop-nav"><a href="#mengapa">Mengapa penting</a><a href="#cara-kerja">Cara kerja</a><a href="#perlindungan">Perlindungan</a></nav><div class="landing-actions"><a class="landing-login" href="{{ route('login') }}">Masuk</a><a class="landing-report" href="{{ route('reports.create') }}"><i data-lucide="shield-plus"></i> Buat laporan</a><details class="landing-mobile-menu"><summary aria-label="Buka menu"><i data-lucide="menu"></i></summary><div><a href="#mengapa">Mengapa penting</a><a href="#cara-kerja">Cara kerja</a><a href="#perlindungan">Perlindungan</a></div></details></div></header>
<main>
<section class="landing-hero"><div class="hero-content"><span class="landing-kicker">PLATFORM PERLINDUNGAN PESERTA DIDIK · KOTA BUKITTINGGI</span><h1>Sekolah aman<br>dimulai dari <em>keberanian</em><br>untuk didengar.</h1><p>SAHABAT SEKOLAH membantu peserta didik melaporkan perundungan dengan aman, dan membantu Guru BK menanganinya secara cepat, terukur, dan penuh kepedulian.</p><div class="hero-actions"><a class="landing-report hero-button" href="{{ route('reports.create') }}">Sampaikan laporan <i data-lucide="arrow-up-right"></i></a><a class="hero-secondary" href="#cara-kerja">Pelajari cara kerja <i data-lucide="arrow-down"></i></a></div></div><div class="hero-art"><div class="hero-art-image"></div><div class="hero-note"><i data-lucide="quote"></i><span>Setiap anak berhak merasa aman di sekolah.</span></div></div></section>
<section class="trust-strip"><span><i data-lucide="map-pin"></i> Kota Bukittinggi</span><span><i data-lucide="lock-keyhole"></i> Identitas dilindungi</span><span><i data-lucide="clock-3"></i> Respons awal 1 × 24 jam</span></section>
<section class="landing-section why-section" id="mengapa"><div class="section-intro"><span class="landing-kicker">MENGAPA INI PENTING</span><h2>Perundungan tidak boleh<br>menjadi hal yang dianggap biasa.</h2><p>Korban dan saksi sering diam karena takut, bingung, atau tidak tahu harus mulai dari mana. Sistem yang aman memberi ruang untuk bicara dan memastikan setiap laporan mendapat tindak lanjut.</p></div><div class="why-grid"><article><span class="feature-icon blue-icon"><i data-lucide="messages-square"></i><b></b></span><h3>Mendengar tanpa menghakimi</h3><p>Setiap laporan diterima sebagai informasi penting untuk memahami dan melindungi peserta didik.</p></article><article><span class="feature-icon yellow-icon"><i data-lucide="fingerprint"></i><b></b></span><h3>Melindungi identitas</h3><p>Pelapor dapat memilih identitas terbuka, rahasia, atau anonim dengan akses berbasis kewenangan.</p></article><article><span class="feature-icon green-icon"><i data-lucide="workflow"></i><b></b></span><h3>Menangani secara terarah</h3><p>Guru BK memperoleh alur verifikasi, penilaian risiko, penanganan, dan dokumentasi yang jelas.</p></article></div></section>
<section class="landing-section process-section" id="cara-kerja"><div class="section-intro centered"><span class="landing-kicker">CARA KERJA</span><h2>Dari laporan menjadi<br>tindakan yang terukur.</h2><p>SAHABAT SEKOLAH menyatukan keberanian untuk melapor dengan tanggung jawab untuk menindaklanjuti.</p></div><div class="process-grid"><div class="process-step"><span>01</span><i data-lucide="message-square-plus"></i><h3>Lapor dengan aman</h3><p>Korban, saksi, atau pihak yang mengetahui kejadian dapat menyampaikan laporan.</p></div><div class="process-line"></div><div class="process-step"><span>02</span><i data-lucide="search-check"></i><h3>Guru BK merespons</h3><p>Laporan diterima, diverifikasi, dan mendapat respons awal maksimal 1 × 24 jam.</p></div><div class="process-line"></div><div class="process-step"><span>03</span><i data-lucide="shield-half"></i><h3>Kasus ditangani</h3><p>Risiko dinilai, tindakan dicatat, dan eskalasi dilakukan bila diperlukan.</p></div><div class="process-line"></div><div class="process-step"><span>04</span><i data-lucide="circle-check"></i><h3>Penyelesaian terdokumentasi</h3><p>Kasus hanya ditutup setelah tersedia bukti penyelesaian yang valid.</p></div></div></section>
<section class="landing-section protection-section" id="perlindungan"><div class="protection-art"><div class="protection-circle"><i data-lucide="lock-keyhole"></i></div><span class="orbit orbit-one"></span><span class="orbit orbit-two"></span></div><div class="protection-copy"><span class="landing-kicker">RUANG YANG LEBIH AMAN</span><h2>Anda tidak harus<br>menghadapi ini sendirian.</h2><p>Laporkan dengan cara yang paling nyaman bagi Anda. Identitas pelapor tidak ditampilkan secara bebas, setiap akses sensitif tercatat, dan Guru BK menjadi pihak utama dalam pendampingan.</p><div class="protection-list"><span><i data-lucide="check"></i> Identified, Confidential, atau Anonymous</span><span><i data-lucide="check"></i> Kanal komunikasi anonim dengan Guru BK</span><span><i data-lucide="check"></i> Bukti dan proses penanganan terdokumentasi</span></div><a class="landing-report hero-button" href="{{ route('reports.create') }}">Mulai membuat laporan <i data-lucide="arrow-up-right"></i></a></div></section>
<section class="closing-band"><span class="landing-kicker">SAHABAT SEKOLAH</span><h2>Mendengarkan. Melindungi. Mendampingi.</h2><p>Untuk sekolah yang lebih aman bagi setiap anak di Kota Bukittinggi.</p><a href="{{ route('login') }}">Masuk ke ruang kerja <i data-lucide="arrow-right"></i></a></section>
</main><footer class="landing-footer"><span>© 2026 Sahabat Sekolah</span><span>Dinas Pendidikan Kota Bukittinggi</span><span>Platform pelaporan dan penanganan perundungan</span></footer><script>lucide.createIcons();</script>
</body>
</html>
