version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sahabat-sekolah-app
    container_name: sahabat-sekolah-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sahabat-network

  web:
    image: nginx:alpine
    container_name: sahabat-sekolah-web
    restart: unless-stopped
    ports:
      - "8209:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - sahabat-network

  db:
    image: postgres:15-alpine
    container_name: sahabat-sekolah-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-sahabat_sekolah}
      POSTGRES_USER: ${DB_USERNAME:-sahabat_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret_password}
    # ports:
      # - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sahabat-network

networks:
  sahabat-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.169.91.0/24

volumes:
  db-data:
