<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inbox Laporan | Sahabat Sekolah</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body>
<div class="inbox-shell">
    <header class="case-topbar"><a class="brand-link" href="{{ url('/') }}"><span class="brand-mark">✦</span><strong>Sahabat Sekolah</strong></a><div class="inbox-actions"><a class="back-link" href="{{ url('/') }}"><i data-lucide="layout-dashboard"></i> Dashboard</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="logout-button" type="submit"><i data-lucide="log-out"></i></button></form></div></header>
    <main class="inbox-main"><div class="inbox-heading"><div><span class="eyebrow">CASE MANAGEMENT</span><h1>Inbox laporan masuk</h1><p>Kelola laporan dalam lingkup sekolah Anda.</p></div><a class="primary-button inbox-new-link" href="{{ route('reports.create') }}"><i data-lucide="plus"></i> Buat laporan</a></div>
        <form class="inbox-filters" method="GET"><div class="search-field"><i data-lucide="search"></i><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Cari nomor, kategori, atau kronologi..."></div><select name="status"><option value="">Semua status</option><option value="PENDING_RESPONSE" @selected(($filters['status'] ?? '') === 'PENDING_RESPONSE')>Menunggu respons</option><option value="UNDER_VERIFICATION" @selected(($filters['status'] ?? '') === 'UNDER_VERIFICATION')>Verifikasi</option><option value="IN_HANDLING" @selected(($filters['status'] ?? '') === 'IN_HANDLING')>Penanganan</option><option value="RESOLVED" @selected(($filters['status'] ?? '') === 'RESOLVED')>Selesai</option><option value="CLOSED" @selected(($filters['status'] ?? '') === 'CLOSED')>Ditutup</option></select><select name="risk_level"><option value="">Semua risiko</option>@foreach (['LOW','MEDIUM','HIGH','CRITICAL'] as $risk)<option value="{{ $risk }}" @selected(($filters['risk_level'] ?? '') === $risk)>{{ $risk }}</option>@endforeach</select><select name="sla_status"><option value="">Semua SLA</option>@foreach (['ON_TIME','WARNING','OVERDUE','COMPLETED'] as $sla)<option value="{{ $sla }}" @selected(($filters['sla_status'] ?? '') === $sla)>{{ $sla }}</option>@endforeach</select><button class="filter-button" type="submit"><i data-lucide="filter"></i> Terapkan</button></form>
        <section class="panel inbox-panel"><div class="inbox-result-heading"><strong>{{ $cases->count() }} laporan ditemukan</strong><span>Terbaru diperbarui lebih dulu</span></div><div class="inbox-table-wrap"><table><thead><tr><th>Nomor kasus</th><th>Kategori</th><th>Pelapor</th><th>Status</th><th>Risiko</th><th>SLA</th><th></th></tr></thead><tbody>@forelse ($cases as $case)<tr><td><strong>{{ $case->case_number }}</strong><small>{{ \Illuminate\Support\Carbon::parse($case->updated_at)->diffForHumans() }}</small></td><td><span class="category-tag">{{ $case->category }}</span></td><td>{{ $case->identity_mode === 'ANONYMOUS' ? 'Anonim' : $case->reporter_role }}</td><td><span class="status {{ strtolower($case->status) }}">{{ str_replace('_', ' ', $case->status) }}</span></td><td><span class="priority {{ strtolower($case->risk_level) }}">{{ $case->risk_level }}</span></td><td><span class="sla-{{ strtolower($case->sla_status) }}">{{ $case->sla_status }}</span></td><td><a class="view-button" href="{{ route('cases.show', $case->case_number) }}">Buka <i data-lucide="arrow-right"></i></a></td></tr>@empty<tr><td colspan="7" class="empty-table">Tidak ada laporan yang sesuai filter.</td></tr>@endforelse</tbody></table></div></section>
    </main>
</div><script>lucide.createIcons();</script>
</body>
</html>
